# Generated by Django 3.2 on 2021-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('duration', models.FloatField()),
                ('image', models.ImageField(default='Images/None/Noimg.png', upload_to='Images')),
            ],
        ),
    ]
